# In Class Practice Session on Introduction to NumPy Arrays: Creation, Operations, and Performance Comparison: Pair-Wise Group Programming

## Submission Due: April 9

Each group of two members should solve the following questions.  

**Incentive:**

The group who solves these questions first will each receive a small reward!

Reference material: Kindly refer to the Reading materials to complete this task:

-- `ReadingMaterial_Computation_on_arrays_ufuncs.ipynb`

-- `ReadingMaterial_Ufunctions_Broadcasting.ipynb`

-- `ReadingMaterials_DateTimeFunctions.ipynb`

-- `Lec_Intro_NumPy.ipynb`

-- Your own curiosity to search for information!

In [2]:
import numpy as np

 **Array Creation and Attributes**

 - **What function would you use to create an array with values ranging from 0 to 5 with a step of 0.5?Use: num_points = int((end - start) / step) + 1 to get the number of data points**

In [36]:
#write your code in this space
x = np.linspace(0, 5, 11)
print(x)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


 **Array Indexing and Slicing**

**How can you extract elements from an array that are greater than 6 using boolean indexing?**

In [40]:
#write your code in this space
x = np.arange(0, 10)
print(x)
mask = x > 6
new = x[mask]
print(new)

[0 1 2 3 4 5 6 7 8 9]
[7 8 9]


 **If you want to slice the first two rows of a 2D array, what syntax would you use?**



In [47]:
#write your code in this space
x = np.array([[0, 1, 2], [3, 4, 5], [5, 6, 7]])
print(x[0:2])

[[0 1 2]
 [3 4 5]]


**What is the purpose of `np.random.seed()`**

Answer: When specifying a seed value, the same random sequence of generated numbers will be the same. This enables you to reproduce the same generated numbers.

















**What does `dtype` tell you about a NumPy array?**










Dtype is short for data type, which describes the data type of the elements in the array.

**What is a ufunction and state one advantage of the utility of ufunctions**

Answer: Universal Functionsare vectorized, allowing operations to the entire arrays without looping elements. This is incredibly much faster for performance and efficiency. 

**What is meant by Braodcasting and where would you use it?**
Answer: Ufuncs supports broadcasting, which performs operations on arrays of different shapes and sizes to automatically adjust to make their dimensions compatible for element-wise operations. For example, an arrary can have each of its elements multipled by a scalar as it broadcasts the operation

**Reshaping Arrays**

- **How would you reshape a 2x3 array into a 3x2 array?**

In [ ]:
#write your code in this space



**After reshaping an array, how can you modify one element in the new array without changing the original array?**

In [ ]:
#write your code in this space




**Array Operations**

- **Write the code to perform element-wise addition of two arrays `a = np.array([10, 20, 30])` and `b = np.array([1, 2, 3])`.**

In [ ]:
#write your code in this space





 - **How would you perform matrix multiplication on two 2x2 matrices in NumPy?**

In [ ]:
#write your code in this space




- **How do you generate an array of random numbers with shape (2, 3) using NumPy?**

In [ ]:
#write your code in this space





 **Array Aggregation Functions**
   - **Write the code to find the sum, max, min, and mean of a 2D NumPy array.**
     

In [ ]:
#write your code in this space

x = np.random.randint(0, 10, size=(5, 2))
print(x)

print("Sum: ", np.sum(x))
print("Mean: ", np.mean(x))
print("Min:", np.min(x))
print("Max:", np.max(x))


[[0 7]
 [2 1]
 [7 1]
 [2 9]
 [1 2]]
Sum:  32
Mean:  3.2
Min: 0
Max: 9


 - **How can you calculate the mean of each column of a 2D array?**

In [17]:
#write your code in this space

print(x)
x.mean(axis=0)


[[0 7]
 [2 1]
 [7 1]
 [2 9]
 [1 2]]


array([2.4, 4. ])

 - **What is the result of adding an integer array to a float array in NumPy? Create two arrays to show your result**

In [ ]:
#write your code in this space
x = np.linspace(0, 20, 5)
print(x)
y = np.arange(0, 21, 5)
print(y)

x + y # both becomes float

[ 0.  5. 10. 15. 20.]
[ 0  5 10 15 20]


array([ 0., 10., 20., 30., 40.])

**Array Creation with Specific Functions**

- **Write the code to create the following array: array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])**

In [ ]:
#write your code in this space





- **How do you create an array with values ranging from 10 (inclusive) to 50 (exclusive), with a step size of 2?**

In [ ]:
#write your code in this space






**Compare the time performance of adding three 50x50 arrays using a Python loop versus using a NumPy universal function (ufunc) by leveraging Python's time module for measuring execution time.**

In [ ]:
#write your code in this space

























