In [89]:
import numpy as np

In [90]:
#generate an array
my_array = np.arange(10) #10 represents the stop value & default start counting from 0
print(my_array)
#print the data type
print(type(my_array))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [91]:
my_arrange = np.arange(1,8)
print(my_arrange)

[1 2 3 4 5 6 7]


In [92]:
#include only the odd digits: start, stop, step
my_array = np.arange(1,10,2)
print(my_array)

[1 3 5 7 9]


In [93]:
#we can also have step size as a floating point
my_array = np.arange(1,10,0.5)

In [94]:
#we can also have negative numbers
my_array = np.arange(-1,9.25,0.5)

#so we can use arange to generate all kinds of sequences
my_array

array([-1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,
        4.5,  5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ])

Arrays can be generated from lists as well

In [95]:
import numpy as np
from_list = np.array([1,2.3,4])
print(from_list)

[1.  2.3 4. ]


### Purpose of converting list to array:
a list can store all kinds of data types such as a list, floating, dictionary, etc. But this flexibility wastes a lot of resources. For example: a boolean takes less ,memory space than a string since it can take only two values. But for a string datatype consider a single character, it can be either 26 lowercase letters, or either one of 26 lowercase letters or either of 10 digits or either one of the 10+ punctuation symbols. So for one single character there are 70+ available options. Thus it may not be efficient to store boolean and string data types in the same list.
On the other hand hand, we can specify the amount of memory space to numpy  arrays inorder to store the data only if they are of the same type.

In [96]:
from_list = np.array([1,2,3])
print(type(from_list[0]))

<class 'numpy.int64'>


Question: Do we really need 64 bits to store these three numbers?
To confirm this, we need to convert these decimal numbers into binary numbers:
```
Decimal    Binary
1            01
2            10
3            11
```

So realistically our biggest number `3` takes only 2 bits. So we don't really need 64 bits to store these three integer (decimal) numbers. We need to specify a data type argument to set the number of bits to store these numbers.

In [97]:
from_list = np.array([1,2,3],dtype = np.int8)
print(type(from_list[0]))

<class 'numpy.int8'>


But just because we are taking less space to store these numbers, it does not mean that our code has become efficient that is it takes less time. Execution or time efficiency depends on the hardware and operating system.

## Multi Dimensional Dimensional Arrays

* Two Dimensional Arrays

-- Option 1: Use two dimensional lists

-- Option 2: Use arange with two arange as a list or tuple

In [98]:
#Option-1: 2D array
import numpy as np
from_list = np.array([[1,2,3],[4,5,6]],dtype = np.int8)
print(from_list)

[[1 2 3]
 [4 5 6]]


In [99]:
#Option-2: using arange passing a list or tuple
array_2d = np.array((np.arange(0,3),np.arange(3,6)))


In [100]:
#verify if it is a two dimensional array or not
print("2D shape:",array_2d.shape)

2D shape: (2, 3)


In [101]:
#Changing the shape of the array using reshape
array_2D = array_2d.reshape(3,2)
print(array_2D)
print("\n")
#or
array_2d = np.arange(0,6).reshape(3,2)
print(array_2d)

[[0 1]
 [2 3]
 [4 5]]


[[0 1]
 [2 3]
 [4 5]]


In [102]:
#flattened array
array_1d = array_2d.reshape(6)
array_1d


array([0, 1, 2, 3, 4, 5])

* Three Dimensional Arrays
```
array.reshape(depth, rows, columns)
```
```
array_3D = np.arange(18).reshape(3,2,3)
```
The first argument (3) is the number of layers or depth (how many 2D matrices you have).

The second argument (2) is the number of rows in each 2D matrix.

The third argument (3) is the number of columns in each row of the 2D matrix.

In [103]:
# Create a 3D matrix with 2x2 matrices
array_3D_2x2 = np.arange(12).reshape(3, 2, 2)
array_3D_2x2

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

**Sometime we don't know which values to store in an array**
So we create empty arrays: Numpy has 4 options:

In [104]:
empty_array1 = np.zeros((2,2))
print(empty_array1)

[[0. 0.]
 [0. 0.]]


In [105]:
empty_array2 = np.ones((2,2))
print(empty_array2)

[[1. 1.]
 [1. 1.]]


In [106]:

empty_array3 = np.empty((2,2))
print(empty_array3) #we get similar results to np.zero()

[[1. 1.]
 [1. 1.]]


In [107]:
#if we change the shape we get different result
empty_array3 = np.empty((2,2,2))
print(empty_array3)
#empty returns random values. PRolematic: since it returns unexpected values

[[[5.13881633e-310 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]]

 [[0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]]]


In [108]:
empty_array4 = np.eye((3))
print(empty_array4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [109]:
#We are not limited to the main diagonal only. We can set the value of 1 above and below the main diagonal
#setting the value 1 below the diagonal using k value
eye_array = np.eye(3,k=-1)
print(eye_array)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [110]:
eye_array = np.eye(3,k=1)
print(eye_array)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


### Random Arrays:

* `np.random.randint(low, high, size)`
Generates a random integer array from a specified range (low to high), with the specified shape (size).

  -- Parameters:

  -- low: Lower bound (inclusive).

  -- high: Upper bound (exclusive).

  -- size: The shape of the output array.



* `np.random.rand(size)`
Generates an array of random floats between 0 and 1, following a uniform distribution. The size specifies the shape of the array.

  -- Parameters:

  -- size: The shape of the output array (e.g., (3, 3) for a 3x3 array).

* `np.random.randn(size)`
Generates a random array with values sampled from a standard normal distribution (mean = 0, standard deviation = 1).

  -- Parameters:

  -- size: The shape of the output array.

* `np.random.uniform(low, high, size)`
Generates a random array with values sampled from a uniform distribution between low and high.

In [111]:
import numpy as np
array = np.random.randint(0, 10, size=(3, 3))
print(array)
#This will generate a 3x3 array of random integers between 0 (inclusive) and 10 (exclusive).


[[0 5 3]
 [2 9 0]
 [8 9 1]]


In [112]:
array = np.random.rand(3, 3)
print(array)
#This will generate a 3x3 array of random floats between 0 and 1.

[[0.9238945  0.52032196 0.43273675]
 [0.86797768 0.34369641 0.84140076]
 [0.64704957 0.0520596  0.75268601]]


In [113]:
array = np.random.randn(3, 3)
print(array)


[[-0.22938795 -0.37002086 -1.16077708]
 [ 0.11696411  0.02179981  0.06443952]
 [ 0.3235947  -0.58883296  1.99496324]]


In [114]:
array = np.random.uniform(0, 10, size=(3, 3))
print(array)


[[2.14533803 3.62835202 7.93896747]
 [8.13237884 4.55515313 1.99858661]
 [6.27030059 4.94706959 2.83681645]]


### Manipulate the values of the eye array

In [115]:
eye_array = np.eye(3,k=1)
eye_array[eye_array == 0] = 5
print(eye_array)

[[5. 1. 5.]
 [5. 5. 1.]
 [5. 5. 5.]]


In [116]:
#change all values which are < 2 to 10
eye_array[eye_array < 2] = 10
print(eye_array)

[[ 5. 10.  5.]
 [ 5.  5. 10.]
 [ 5.  5.  5.]]


## Array Slicing

In [117]:
eye_array[:2] = 3 #selecting first two rows

In [118]:
#selecting all last rows except for the first row
eye_array[1:] = 5

In [119]:
#change only the second column to 2
eye_array[:,1]=2

In [120]:
#we can select from the end of the array: change the last column
eye_array[:,-1] = 4

In [121]:
#select the last two rows and first 2 columns and change the values to -1
eye_array[1:,:2] = -1
print(eye_array)

[[ 3.  2.  4.]
 [-1. -1.  4.]
 [-1. -1.  4.]]


## Sort Arrays

In [125]:
print("original Array","\n")
print(eye_array)

print("second sort")
sorted = np.sort(eye_array)
print(sorted) #quick sort sorting by rows default -1 (either rows or colm)
#comparing with th original array

print("\nSorting by Colm")
sorted = np.sort(eye_array,axis = 0)
print(sorted)
#other sorting algorithm
#np.sort(eye_array,axis = 0,kind="mergesort")

original Array 

[[ 3.  2.  4.]
 [-1. -1.  4.]
 [-1. -1.  4.]]
second sort
[[ 2.  3.  4.]
 [-1. -1.  4.]
 [-1. -1.  4.]]

Sorting by Colm
[[-1. -1.  4.]
 [-1. -1.  4.]
 [ 3.  2.  4.]]


### copy arrays - duplicates of an array can be created by two methods
* view(): any modifications to the values of a duplicate of the original array will also modify the values within the original array. No modifications of the shape happens if we change the shape

* copy(): any modifications to a duplicate of the original will not  modify the values of the original array

In [123]:
my_view = sorted_array.view()
my_copy = sorted_array.copy()

#assign all values of my_view to 4
my_view[:] = 4
print(my_view,"\n")
print(sorted_array) #we see that we have modified the original array

NameError: name 'sorted_array' is not defined

In [ ]:
#assign all values of my_copy to 4
my_copy[:] = 4
print(my_copy,"\n")
print(sorted_array)

In [ ]:
#will shape of the original array change if we change the chape of the duplicate via the view array method?
my_view = my_view.reshape(3,3,1)
print(my_view,"\n")
print(sorted_array)