Book: Python Data Science Handbook:

https://github.com/jakevdp/PythonDataScienceHandbook

**Task:** For each line of code, add a comment in your own words describing what that statement does. For example: `np.arange(1, 5)  # generates integers from 1 (inclusive) to 5 (exclusive)`


In [2]:
import numpy as np

A numpy array is sort of like a list:

### Creating arrays

ndarrays are typically created using two main methods:
1. From existing data (usually lists or tuples) using `np.array()`, like we saw above; or,
2. Using built-in functions such as `np.arange()`, `np.linspace()`, `np.zeros()`, etc.

Just like you can have "multi-dimensional lists" (by nesting lists in lists), you can have multi-dimensional arrays. Write the code to Create a multi-dimensional numpy array of you choice.  

In [ ]:
np.arange(1, 7) # from including 1 to  excluding 7, return all indexes between

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.arange(0, 11, 2) # steps of 2 starting from 0

array([ 0,  2,  4,  6,  8, 10])

In [23]:
np.arange(1, 15, 3)

array([ 1,  4,  7, 10, 13])

In [30]:
np.linspace(0, 10, 10) # 10 evenly spaced values between 0 and 10 

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [31]:
np.linspace(1, 10, 10) # 10 evenly spaced values between 1 and 10 

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [29]:
np.linspace(0, 10, 20) # 20 evenly spaced evalues between 0 and 10 

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
np.ones((2, 2)) # (x, y) where there are x number of 1s and y number of 1s

array([[1., 1.],
       [1., 1.]])

In [33]:
np.ones((3, 2, 3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
np.zeros((2, 3)) 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.full((3, 3), 3.14) #np.full(tuple, val); tuple is the matrix shape

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [9]:
np.full((3, 3, 3), 3.14)

array([[[3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14]],

       [[3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14]],

       [[3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14]]])

In [81]:
np.random.rand(5, 2)

array([[0.50146397, 0.95424625],
       [0.23961338, 0.44890314],
       [0.18060505, 0.79283792],
       [0.58613614, 0.15523133],
       [0.06572246, 0.23659718]])

In [ ]:
x = np.random.rand(5, 2) # generate random values of a 5x2 matrix
x

array([[0.50895576, 0.5293743 ],
       [0.29490365, 0.92651717],
       [0.33015624, 0.7404551 ],
       [0.91501725, 0.31869092],
       [0.8586952 , 0.46594522]])

In [ ]:
x.transpose() # from 5x2 to 2x5

array([[0.50895576, 0.29490365, 0.33015624, 0.91501725, 0.8586952 ],
       [0.5293743 , 0.92651717, 0.7404551 , 0.31869092, 0.46594522]])

In [ ]:
x.mean() # sum of all elements divided by total number of elements

np.float64(0.5888710798911585)

In [ ]:
x.astype(int) # disregards the decimal values; just the integer; no rounding

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [86]:
test = np.array([1.2, 2.3, 3.4])
print(test)
test.astype(int)

[1.2 2.3 3.4]


array([1, 2, 3])

As you just saw above, arrays can be of any dimension, shape and size you desire. In fact, there are three main array attributes you need to know to work out the characteristics of an array:
- `.ndim`: the number of dimensions of an array
- `.shape`: the number of elements in each dimension (like calling `len()` on each dimension)
- `.size`: the total number of elements in an array (i.e., the product of `.shape`)

In [101]:
import numpy as np  # import the NumPy library for numerical operations

# Create a 1D array of length 3
print("1D Arrays")
arr = np.random.rand(3)
print(arr)

arr = np.random.randint((3), size=(3))
print(arr)

arr = np.array([1, 2, 3])
print(arr)

# Create a 2D column vector (3×1)
print("\n2D Arrays")
arr = np.random.rand(3, 1)
print(arr)

arr = np.random.randint(5, size=(3, 1))
print(arr)

arr = np.array([[1], [2], [3]])
print(arr)
# Add the 1D array `a` to each row of the column vector `b` via broadcasting

# `a` (shape (3,)) is broadcast to shape (3,3) to match `b` (shape (3,1))


1D Arrays
[0.49554272 0.6969972  0.37583105]
[2 1 2]
[1 2 3]

2D Arrays
[[0.65103219]
 [0.73985699]
 [0.60962393]]
[[0]
 [3]
 [2]]
[[1]
 [2]
 [3]]


**Practice Task**:

* Change a to be `np.array([2, 4, 6, 8])` and `b` to be `np.array([[10], [20]])`.

* Explain (next to each line) why the shapes are or are not compatible for broadcasting.

In [16]:


# Create a 1D float array


# Apply the sine ufunc to every element of x


# Square each element of y using a ufunc


# Compute the exponential of each element in z



Practice Task:

Replace `np.sin(x)` with `np.log(x + 1)` and explain why we added +1 inside the log.

Use `np.maximum(y, 0.5)` on the `y` array to threshold all values below 0.5 to 0.5. Write a comment for that line.

In [17]:


# Create a Pandas Series from a Python list
data = [100, 200, 300, 400]            # a simple Python list of integers
s = pd.Series(data)                    # s is now a Series: 0→100, 1→200, 2→300, 3→400

# Create a Series with a custom index
labels = ['a', 'b', 'c', 'd']          # custom index labels
s2 = pd.Series(data, index=labels)     # s2 is now a Series: a→100, b→200, c→300, d→400

# Access element by position
val_pos = s[2]                         # val_pos = 300 (integer at position 2)

# Access element by label
val_lbl = s2['c']                      # val_lbl = 300 (integer at label 'c')

# Perform vectorized arithmetic on the Series
s3 = s + 50                            # adds 50 to each element: [150, 250, 350, 450]


NameError: name 'pd' is not defined

* Practice Task:

Create a Series of floating‐point values `[1.5, 2.5, 3.5]` with index `['x', 'y', 'z']`.

Multiply that Series by 2 and explain in a comment what happens to both values and index.

In [ ]:


# Construct a DataFrame from a dictionary of lists: list of names, list of ages, list of float scores

df = pd.DataFrame(dict_data)                  # df is now a DataFrame with columns 'Name', 'Age', 'Score'

# display the first 5 rows (here only 3 rows exist)

# Add a new column 'AgePlusFive' by doing arithmetic on existing columns: increase current age by 5


# Compute the mean of the 'Score' column


# Filter rows where Score is greater than 80


- Create a DataFrame with columns ['Item', 'Price', 'Quantity'] of your own choosing (at least 4 rows).

- Add a column 'TotalValue' = Price * Quantity and comment on what that line does.

- Filter out all rows where 'TotalValue' < 50 and explain.

In [ ]:
import pandas as pd  # import pandas for data manipulation

# Create a sample DataFrame with categories and values
data = {
    'Department': ['Sales', 'Sales', 'HR', 'HR', 'IT', 'IT', 'IT'],  # department labels
    'Employee': ['E1', 'E2', 'E3', 'E4', 'E5', 'E6', 'E7'],          # employee IDs
    'Salary': [50000, 55000, 45000, 47000, 60000, 62000, 61000]       # salaries
}
df = pd.DataFrame(data)                                           # create the DataFrame

# Group rows by 'Department'
grouped = df.groupby('Department')                                 # returns a GroupBy object

# Compute the average salary in each department
avg_salary = grouped['Salary'].mean()                               # Series: avg salary per department

# Compute multiple aggregations (min, max, and sum) on 'Salary'
agg_salary = grouped['Salary'].agg(['min', 'max', 'sum'])           # DataFrame with min, max, sum per department

# Get the number of employees in each department
count_employees = grouped['Employee'].count()                        # Series: count of employees per dept


Practice Task:

- Using the same df, compute the median salary per department and comment on your code.

- Add a new column 'YearsAtCompany' with hypothetical values, then find the total years per department using .sum(). Explain each line.

In [ ]:
import pandas as pd  # import pandas to create pivot tables

# Create a DataFrame showing sales of products in different regions and quarters
data = {
    'Region': ['North', 'North', 'South', 'South', 'East', 'East', 'West', 'West'],  # region labels
    'Quarter': ['Q1', 'Q2', 'Q1', 'Q2', 'Q1', 'Q2', 'Q1', 'Q2'],                    # quarter labels
    'Product': ['A', 'A', 'B', 'B', 'A', 'B', 'A', 'B'],                             # product IDs
    'Revenue': [200, 250, 180, 210, 220, 230, 190, 205]                              # revenue numbers
}
df = pd.DataFrame(data)  # create the DataFrame

# Create a pivot table summarizing revenue by Region (rows) and Product (columns)
pivot1 = df.pivot_table(
    values='Revenue',            # values to aggregate
    index='Region',              # rows
    columns='Product',           # columns
    aggfunc='sum',               # how to aggregate
    fill_value=0                 # replace missing entries with 0
)
# pivot1 looks like:
# Product    A    B
# Region
# East     220  230
# North    450    0
# South      0  390
# West     190  205

# Create another pivot table that shows average revenue per quarter and product
pivot2 = df.pivot_table(
    values='Revenue',            # values to aggregate
    index='Quarter',             # rows
    columns='Product',           # columns
    aggfunc='mean',              # average
    margins=True                 # add row/column totals
)
# pivot2 looks like:
# Product       A      B    All
# Quarter
# Q1        203.333  189.333  392.667
# Q2        235.000  215.000  450.000
# All       219.167  202.167  421.333


Practice Task:

- What is a Pivot table?

- Using the same df, create a pivot table that shows maximum revenue by Region and Quarter. Comment each line.

- Explain in a comment what `margins=True` does in a pivot table.

In [ ]:
import numpy as np    # import NumPy for numerical array operations
import pandas as pd   # import pandas for DataFrame creation

# 1. Generate random data for 5 days of sales of 3 different items
np.random.seed(42)                       # seed the RNG so results are reproducible
sales_array = np.random.randint(10, 100, size=(5, 3))
# sales_array is a 5×3 array of random integers between 10 (inclusive) and 100 (exclusive)

# 2. Create a Date index for those 5 days
dates = pd.date_range(start='2025-06-01', periods=5, freq='D')
# dates is a DatetimeIndex: 2025-06-01, 2025-06-02, …, 2025-06-05

# 3. Build a DataFrame from the NumPy array, using dates as the index and item names as columns
items = ['ItemA', 'ItemB', 'ItemC']       # list of column names
df_sales = pd.DataFrame(sales_array, index=dates, columns=items)
# df_sales now looks like:
#             ItemA  ItemB  ItemC
# 2025-06-01     52     93     15
# 2025-06-02     72     61     21
# 2025-06-03     83     87     75
# 2025-06-04     89     13     10
# 2025-06-05     26     55     15

# 4. Calculate the total sales per day (sum across columns)

# adds a 'Total' column: each row is the sum of ItemA + ItemB + ItemC for that date

# 5. Find the average sales for each item over the 5-day period

# returns a Series with avg of ItemA, ItemB, ItemC over all dates

# 6. Suppose a promotion doubles all sales for ItemB; apply broadcasting to update only ItemB



# 7. Recompute the daily totals after the promotion



Practice Task:

- Before Step 6, create a new column 'DiscountedA' equal to 80% of ItemA sales (i.e., multiply ItemA by 0.8). Comment on that line.

- After Step 7, filter the DataFrame to show only the days where 'NewTotal' > 200 and explain how your filtering works.

**Answer the following questions:**

- How does NumPy broadcasting or a Pandas method work in this context?

- What is the effect of each arithmetic or aggregation operation?

- What is the meaning of the following arguments:  `axis=1`, `aggfunc='sum'`, `fill_value=0` ?