# Introductory NumPy lab: Please attempt all the questions and demo your answers to your intructor/TA within the due date.

Learning Objectives of this Lab:

* Create, manipulate, and reshape NumPy arrays.

* Perform statistical analysis and aggregation on arrays.

* Work with random data and array slicing.

* Understand and use array operations such as element-wise operations, conditional replacements, and aggregation.

* Gain practical skills with NumPy functions that are critical for data manipulation in Python.

These learning outcomes of these exercises are to provide students with a strong foundation in using NumPy for data manipulation, which will be essential for future data science, machine learning, and scientific computing applications.

# 1. Create a 3x3x3 array with random values

In [1]:
import numpy as np

np.random.random((3, 3, 3))

array([[[0.12659441, 0.24628528, 0.2167974 ],
        [0.5334671 , 0.51664095, 0.20893097],
        [0.49402135, 0.95335071, 0.55342676]],

       [[0.54295363, 0.4230351 , 0.01645177],
        [0.1957041 , 0.49585085, 0.50435852],
        [0.66674095, 0.56537115, 0.15329257]],

       [[0.87407814, 0.74313602, 0.15146318],
        [0.38955863, 0.08391863, 0.34408091],
        [0.63632613, 0.28010763, 0.33248849]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
np.array([[0, 0, 0, 0, 0],
         [1, 0, 0, 0, 0],
         [0, 2, 0, 0, 0],
         [0, 0, 3, 0, 0],
         [0, 0, 0, 4, 0]])

eye_array = np.eye(5,k=-1)
print(eye_array)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
np.array([[0, 1, 0, 1, 0, 1, 0, 1],
          [1, 0, 1, 0, 1, 0, 1, 0],
          [0, 1, 0, 1, 0, 1, 0, 1],
          [1, 0, 1, 0, 1, 0, 1, 0],
          [0, 1, 0, 1, 0, 1, 0, 1],
          [1, 0, 1, 0, 1, 0, 1, 0],
          [0, 1, 0, 1, 0, 1, 0, 1],
          [1, 0, 1, 0, 1, 0, 1, 0],])

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [4]:
# Normalize entire matrix by rows
df = np.random.randint(0, 10, size=(5, 5), dtype=int)
print(df)
dfmin = df.min()
dfmax = df.max()
(df-dfmin) / (dfmax - dfmin)

[[1 3 3 4 3]
 [4 1 6 2 2]
 [9 3 2 1 4]
 [9 9 3 4 8]
 [7 9 7 3 3]]


array([[0.   , 0.25 , 0.25 , 0.375, 0.25 ],
       [0.375, 0.   , 0.625, 0.125, 0.125],
       [1.   , 0.25 , 0.125, 0.   , 0.375],
       [1.   , 1.   , 0.25 , 0.375, 0.875],
       [0.75 , 1.   , 0.75 , 0.25 , 0.25 ]])

In [5]:
# Normalize entire matrix by columns
df = np.random.randint(0, 10, size=(5, 5), dtype=int)
print(df)
dfmin = df.min(axis = 0)
dfmax = df.max(axis = 0)
(df-dfmin) / (dfmax - dfmin)

[[1 8 2 0 1]
 [5 0 7 9 9]
 [5 7 5 3 5]
 [3 0 4 2 7]
 [2 6 1 1 1]]


array([[0.        , 1.        , 0.16666667, 0.        , 0.        ],
       [1.        , 0.        , 1.        , 1.        , 1.        ],
       [1.        , 0.875     , 0.66666667, 0.33333333, 0.5       ],
       [0.5       , 0.        , 0.5       , 0.22222222, 0.75      ],
       [0.25      , 0.75      , 0.        , 0.11111111, 0.        ]])

# 5.  How to find common values between two arrays?

refer and study the method `intersect1d`

In [6]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 6, 7, 8, 1])
print(arr1 == arr2)
np.intersect1d(arr1, arr2)

[False False False False False]


array([1, 5])

# 6.How to get the dates of yesterday, today and tomorrow?

In [7]:
# https://www.w3resource.com/python-exercises/numpy/python-numpy-datetime-exercise-2.php

print("Today:", np.datetime64('today'))
print("Yesterday:", np.datetime64('today') - np.timedelta64(1))
print("Tomorrow:", np.datetime64('today') + np.timedelta64(1))

Today: 2025-04-14
Yesterday: 2025-04-13
Tomorrow: 2025-04-15


# 7. Consider two random array A and B, check if they are equal

In [8]:
arrA = np.random.randint(0, 10, size=(1, 5), dtype=int)
arrB = np.random.randint(0, 10, size=(1, 5), dtype=int)
print(arrA)
print(arrB)
np.array_equal(arrA, arrB)


[[7 4 8 3 5]]
[[6 8 5 0 9]]


False

# 8.Create random vector of size 20 and replace the maximum value by 1 and minimum value by -1

In [9]:
df = np.random.random(20)
print(df)
df[df == df.max()] = 1
df[df == df.min()] = -1
df

[0.24979485 0.56233321 0.82327942 0.89737531 0.02576431 0.30266754
 0.21099106 0.00265685 0.46198749 0.93512353 0.27173209 0.31261119
 0.6369188  0.66357911 0.38670866 0.35519114 0.76187819 0.84822214
 0.1179258  0.25732723]


array([ 0.24979485,  0.56233321,  0.82327942,  0.89737531,  0.02576431,
        0.30266754,  0.21099106, -1.        ,  0.46198749,  1.        ,
        0.27173209,  0.31261119,  0.6369188 ,  0.66357911,  0.38670866,
        0.35519114,  0.76187819,  0.84822214,  0.1179258 ,  0.25732723])

# 9. How to print all the values of an array?

In [10]:
print(np.random.random((5, 5)))

[[0.67700187 0.13809249 0.81895441 0.09651242 0.99922345]
 [0.92041441 0.5003309  0.94124795 0.40962638 0.66821941]
 [0.40465541 0.39246117 0.51514712 0.73277309 0.09888666]
 [0.36497609 0.38068274 0.9987671  0.17593758 0.405088  ]
 [0.39405738 0.12892051 0.19279198 0.58702535 0.84635864]]


# 10.Subtract the mean of each row of a matrix

In [11]:
# https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-182.php

x = np.arange(1, 10).reshape(3, 3)
print(x)
print(x.mean(axis=1))
print(x.mean(axis=1).reshape(3, 1))
y = x-x.mean(axis=1).reshape(3, 1)
y

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2. 5. 8.]
[[2.]
 [5.]
 [8.]]


array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?


In [36]:
x = np.random.randint(0, 10, 10)
print(x)
second_vector = np.ones(10)
print(second_vector)
print(x + second_vector)


[3 6 2 6 4 7 0 9 7 3]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 4.  7.  3.  7.  5.  8.  1. 10.  8.  4.]


# 12.How to get the diagonal of a dot product?

In [13]:
a = np.arange(6).reshape(2, 3)
print(a)
b = np.arange(9).reshape(3, 3)
print(b)


print("dot product of a, b")
print(np.dot(a, b))

# print("dot product")
# print(np.dot(np.dot(a, b), a.T))

np.diag(np.dot(a, b))

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
dot product of a, b
[[15 18 21]
 [42 54 66]]


array([15, 54])

# 13.How to find the most frequent value in an array?

In [35]:
a = np.random.randint(10, size=(1, 10))
print(a)

uniq, freq = np.unique(a, return_counts=True)
print(uniq, freq)
print(freq.argmax()) #returns the index of the highest value
print(uniq[freq.argmax()])

[[1 4 9 9 7 3 8 3 7 3]]
[1 3 4 7 8 9] [1 3 1 2 1 2]
1
3


# 14.How to create a record array from a regular array?

In [15]:
a = np.random.randint(0, 10, size=(3, 5))
print(a)

record = np.rec.array(a)
record

[[8 0 9 1 9]
 [1 7 6 2 0]
 [9 3 9 6 9]]


rec.array([[8, 0, 9, 1, 9],
           [1, 7, 6, 2, 0],
           [9, 3, 9, 6, 9]],
          dtype=int64)

## 15. Create an array with values ranging from 0 to 1 with a step of 0.1.

In [16]:
# num_points = int((end - start) / step) + 1
# 1 / 0.1 + 1 = 11
x = np.linspace(0, 1, 11)
print(x)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


# 16. Create a 5x5 matrix and replace all the even numbers with 0.

In [17]:
x = np.arange(1, 26).reshape(5, 5)
x[x % 2 == 0] = 0

print(x)


[[ 1  0  3  0  5]
 [ 0  7  0  9  0]
 [11  0 13  0 15]
 [ 0 17  0 19  0]
 [21  0 23  0 25]]


# 17. Create an array with values 1 to 9, and then use np.reshape() to reshape it into a 3x3 matrix. Study the `reshape()` method to answer this question



In [18]:
x = np.arange(1, 10).reshape(3, 3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 18. Create a 1D array of random values and find the standard deviation and variance of the array. You can use Python's inbuilt methods `np.std()` and `np.var()` or write your own code for these methods.



In [19]:
x = np.random.randint(0, 10, size=(10))
print(x)

std = np.std(x)
print(std)

var = np.var(x)
print(var)

[8 8 2 7 4 3 2 0 0 7]
3.014962686336267
9.09


# 19. Given an array of numbers, find the indices where the value is greater than a given threshold. Refer to how the method `np.where()` works to answer this question.



In [20]:
x = np.random.randint(0, 10, size=(10))
print(x)
y = np.where(x < 5)
print(y)

[2 5 4 7 0 8 6 2 1 3]
(array([0, 2, 4, 7, 8, 9]),)


# 20. Create two random arrays of size 3x3 and compute their element-wise addition and subtraction.

In [21]:
arr1 = np.random.randint(0, 10, size=(3, 3))
print(arr1)
arr2 = np.random.randint(0, 10, size=(3, 3))
print(arr2)

print("addition:", arr1 + arr2)
print("subtraction:", arr1 - arr2)


[[8 6 5]
 [3 7 2]
 [8 8 2]]
[[3 8 5]
 [5 5 1]
 [5 6 7]]
addition: [[11 14 10]
 [ 8 12  3]
 [13 14  9]]
subtraction: [[ 5 -2  0]
 [-2  2  1]
 [ 3  2 -5]]


Practice Problems

In [22]:
# Generate an array of shape 5 by 5 containin random numbers from uniform distribution
np.random.uniform(size=(5, 5))

array([[0.48383122, 0.30433452, 0.83288809, 0.49705919, 0.28194643],
       [0.34562534, 0.05457879, 0.40697752, 0.00214333, 0.54955857],
       [0.0685121 , 0.83146635, 0.33045862, 0.18978598, 0.44993144],
       [0.18594013, 0.40896631, 0.34616929, 0.46795428, 0.82864089],
       [0.33871559, 0.15049671, 0.78587468, 0.86633219, 0.81305929]])

In [23]:
# Generate an array of shape 5 by 5 containing all one's in the diagonal
eye_array = np.eye(5, 5)
eye_array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
# Modify the off-diagonal elements to contain the value 10
eye_array[eye_array == 0] = 10
eye_array

array([[ 1., 10., 10., 10., 10.],
       [10.,  1., 10., 10., 10.],
       [10., 10.,  1., 10., 10.],
       [10., 10., 10.,  1., 10.],
       [10., 10., 10., 10.,  1.]])