In [2]:
import numpy as np


In [3]:
arr1 = np.random.randint(0, 10, size=(3, 3))
print(arr1)
arr2 = np.random.randint(0, 10, size=(3, 3))
print(arr2)

print("addition:", arr1 + arr2)
print("subtraction:", arr1 - arr2)


[[4 9 4]
 [3 1 5]
 [3 8 0]]
[[5 8 7]
 [5 3 2]
 [9 0 9]]
addition: [[ 9 17 11]
 [ 8  4  7]
 [12  8  9]]
subtraction: [[-1  1 -3]
 [-2 -2  3]
 [-6  8 -9]]


In [4]:
b1 = np.random.rand(3, 2) # 3x2 random 0-1
print("b1", b1)

b2 = np.random.rand(2, 3) # 2x3 random 01
print("b2", b2)

test = np.random.randint(3, 4) # random integer from 3-4
print(test)

b1 [[0.01966696 0.07341023]
 [0.60706548 0.56865249]
 [0.76164945 0.69608927]]
b2 [[0.50152888 0.53790674 0.35019488]
 [0.69187306 0.70015687 0.71168753]]
3


In [5]:




# https://numpy.org/doc/stable/reference/generated/numpy.linspace.html
b5 = np.linspace(1, 6)  
print(b5)

b5 = np.linspace(1, 6, 6)
print(b5)
print(b5.shape)

b6 = b5.reshape(2, 3)
print(b6)



x = np.linspace(0, 1, 10) 
print(x)

# num_points = int((end - start) / step) + 1
# 1 / 0.1 + 1 = 11
x = np.linspace(0, 1, 11)
print(x)



[1.         1.10204082 1.20408163 1.30612245 1.40816327 1.51020408
 1.6122449  1.71428571 1.81632653 1.91836735 2.02040816 2.12244898
 2.2244898  2.32653061 2.42857143 2.53061224 2.63265306 2.73469388
 2.83673469 2.93877551 3.04081633 3.14285714 3.24489796 3.34693878
 3.44897959 3.55102041 3.65306122 3.75510204 3.85714286 3.95918367
 4.06122449 4.16326531 4.26530612 4.36734694 4.46938776 4.57142857
 4.67346939 4.7755102  4.87755102 4.97959184 5.08163265 5.18367347
 5.28571429 5.3877551  5.48979592 5.59183673 5.69387755 5.79591837
 5.89795918 6.        ]
[1. 2. 3. 4. 5. 6.]
(6,)
[[1. 2. 3.]
 [4. 5. 6.]]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [ ]:
a6 = np.ones(5)
print(a6.shape)
print(a6.shape[0])
print(a6.ndim)

(5,)
5
1


In [7]:
x5 = np.arange(1, 10, 2)
print(x5)
print(x5.shape)
x5 = np.arange(1, 10, 2).reshape(1, 5)
print(x5)
print(np.all(x5 % 2 == 0)) # all elements of array


[1 3 5 7 9]
(5,)
[[1 3 5 7 9]]
False


### Label-based Extraction: Indexing with `.loc`

For the more complex task of extracting data with specific column or index labels, we can use `.loc`.   In Pandas, `.loc[]` is an accessor method used to access rows and columns in a DataFrame by label (not by position).

The **labels** (commonly referred to as the **indices**) are the bold text on the far *left* of a `DataFrame`, while the **column labels** are the column names found at the *top* of a `DataFrame`.
```
df.loc[row_label, column_label]
```

To grab data with `.loc`, we must specify the row and column label(s) where the data exists. The row labels are the first argument to the `.loc` function; the column labels are the second.

Arguments to `.loc` can be:

- A single value.
- A slice.
- A list.


### Integer-based Extraction: Indexing with `.iloc`

Slicing with `.iloc` works similarly to `.loc`. However, `.iloc` uses the *index positions* of rows and columns rather than the labels (think to yourself: **loc** uses **lables**; **iloc** uses **indices**). The arguments to the `.iloc` function also behave similarly — single values, lists, indices, and any combination of these are permitted.



###   `.loc[]` vs `.iloc[]`?

| Feature     | `.loc[]`                 | `.iloc[]`               |
|-------------|--------------------------|--------------------------|
| Access by   | **Label**                | **Integer position**     |
| Example     | `df.loc["A"]`            | `df.iloc[0]`             |

---


In [8]:
import pandas as pd
d = {'1': 'Alice', '2': 'Bob', '3': 'Rita',
'4': 'Molly', '5': 'Ryan'}
S = pd.Series(d)

print("iloc: ")
print(S.iloc[0])
print(S.loc["1"])

print("other thing")
print(S.iloc[0:3])
print(S.loc["1": "3"])

print("seaprarate")
print(S.iloc[:3])
print(S.iloc[1:4])
print(S.iloc[:2])


#iloc = integer location - selects rows and columns by position, not label
# first arg : - selects all rows 
# second arg :2 - select columns starting fromm 0 up to (but not including 2)

iloc: 
Alice
Alice
other thing
1    Alice
2      Bob
3     Rita
dtype: object
1    Alice
2      Bob
3     Rita
dtype: object
seaprarate
1    Alice
2      Bob
3     Rita
dtype: object
2      Bob
3     Rita
4    Molly
dtype: object
1    Alice
2      Bob
dtype: object


In [9]:
# Example DataFrame
data = {'A': [1, np.nan, 3, 4],
        'B': [np.nan, 5, 6, 4],
        'C': [7, 8, np.nan, 4],
        'D': [1, 2, 3, 4]}

example_df1 = pd.DataFrame(data)
example_df2 = pd.DataFrame(data)

print(example_df1)


     A    B    C  D
0  1.0  NaN  7.0  1
1  NaN  5.0  8.0  2
2  3.0  6.0  NaN  3
3  4.0  4.0  4.0  4


In [10]:
mask = example_df1.isnull()
print(mask)
print(mask.dtypes)

       A      B      C      D
0  False   True  False  False
1   True  False  False  False
2  False  False   True  False
3  False  False  False  False
A    bool
B    bool
C    bool
D    bool
dtype: object


In [11]:
df1_cleaned1 = example_df1.dropna() # removes ROWS with missing values
print(df1_cleaned1)

     A    B    C  D
3  4.0  4.0  4.0  4


In [12]:
df1_cleaned2 = example_df1.dropna(axis=1) # removes COLUMNS with missing values
print(df1_cleaned2)

   D
0  1
1  2
2  3
3  4


In [13]:

# Replacing NaN values with 199
example_df2.fillna(199, inplace=True)

print(example_df2)

       A      B      C  D
0    1.0  199.0    7.0  1
1  199.0    5.0    8.0  2
2    3.0    6.0  199.0  3
3    4.0    4.0    4.0  4


You are given the following toy dataset representing sales data for a small store. Some of the
values are missing (represented by NaN). Which method would you use to impute the missing
values in the Sales and Profit columns, and why?

In [14]:
store = {"Product": ["A", "B", "C", "D", "E"],
         "Sales": [100, np.nan, 150, np.nan, 200],
         "Profit": [20, 30, np.nan, 40, 50]}
dfstore = pd.DataFrame(store)
dfstore.head()

Product  Sales  Profit
0       A  100.0    20.0
1       B    NaN    30.0
2       C  150.0     NaN
3       D    NaN    40.0
4       E  200.0    50.0

In [15]:
dfstore = dfstore.dropna(subset=['Sales', "Profit"])
dfstore


Product  Sales  Profit
0       A  100.0    20.0
4       E  200.0    50.0

In [16]:
# mean imputation

meansales = dfstore["Sales"].mean()
print(meansales)
dfstore["Sales"] = dfstore["Sales"].fillna(meansales)
dfstore.head()

150.0


Product  Sales  Profit
0       A  100.0    20.0
4       E  200.0    50.0

In [17]:
meanprofit = dfstore["Profit"].mean()
print(meanprofit)
dfstore["Profit"] = dfstore["Profit"].fillna(meanprofit)
dfstore.head()

35.0


Product  Sales  Profit
0       A  100.0    20.0
4       E  200.0    50.0

Calculating loss example: Practice
- Consider weight = -3.6 and bias = 30
- If the model predicts that a 2,370-pound car gets 21.5 miles per gallon, but it actually gets 24 miles
per gallon,
- Calculate the loss: (target – predicted)^2

In [18]:
# y = w*x + b -> 21.5 = -3.6 * 2370 + 30
predicted = 30 + (-3.6 * 2.37)
print(predicted)
loss = (24 - 21.5) ** 2
print(loss)

21.468
6.25


In [19]:
# Example DataFrame
data = {'A': [1, np.nan, 3, 4],
        'B': [np.nan, 5, 6, 4],
        'C': [7, 8, np.nan, 4],
        'D': [1, 2, 3, 4]}

example_df1 = pd.DataFrame(data)

In [20]:
example_df1

A    B    C  D
0  1.0  NaN  7.0  1
1  NaN  5.0  8.0  2
2  3.0  6.0  NaN  3
3  4.0  4.0  4.0  4

In [21]:
# 8.Create random vector of size 20 and replace the maximum value by 1 and minimum value by -1
import random
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
print(arr)

arr[arr == arr.min()] = -1
arr[arr == arr.max()] = 1
arr

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([-1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19,  1])

In [22]:
arr = np.random.randint(1, 21, size=(1, 20), dtype=int)
print(arr)

print("Returns an array of elements only once (no dups)", np.unique(arr)) 
uniq, freq = np.unique(arr, return_counts=True)
print("Frequency of each element at their index based on uniq array", freq)
print(freq.argmax())
print(uniq[freq.argmax()])

[[18  8 12  5  8  6  8 12 17  9  6 10  8 13 12 19 20  5  3 13]]
Returns an array of elements only once (no dups) [ 3  5  6  8  9 10 12 13 17 18 19 20]
Frequency of each element at their index based on uniq array [1 2 2 4 1 1 3 2 1 1 1 1]
3
8
